[package]
name = "escrow_program"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayref = "0.3.6"
solana-program = "1.15.0"
spl-token = { version = "3.5.0", features = ["no-entrypoint"] }
thiserror = "1.0.38"

[lib]
crate-type = ["cdylib", "lib"]
