[programs.localnet]
solana_escrow_anchor = "6t25kse63gnKd1j5vYXvRVjDe78pZQn2HxashQcuSXVw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/saicharanpogul/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-setup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Setup'"
test-alice = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Alice'"
test-bob = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Bob'"
